status=Ontology Specification
ontologyNamespaceURI=https://w3id.org/dqvch#
ontologyPrefix=dqvch
prefix=dqvch
ontologyTitle=Data Quality Vocabulary for Cultural Heritage (DQVCH)
authors=Markus Matoni;Arno Kesper;Gabriele Taentzer
authorsURI=https://orcid.org/0000-0003-4389-5871;https://orcid.org/0000-0002-5042-1087;https://orcid.org/0000-0002-3975-5238
licenseURI=https://creativecommons.org/licenses/by/4.0/
licenseName=CC BY 4.0
licenseIconURL=https://i.creativecommons.org/l/by/4.0/88x31.png
dateCreated=2025-12-01
dateIssued=2026-05-11
thisVersionURI=https://w3id.org/dqvch/1.0.0
latestVersionURI=https://w3id.org/dqvch#
ontologyRevisionNumber=1.0.0
